version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379" 
    command: redis-server --appendonly yes
    environment:
      - REDIS_MAXMEMORY=50mb

volumes:
  redis_data: